name = "FlexiMaps"
uuid = "6394faf6-06db-4fa8-b750-35ccc60383f7"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.12"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[weakdeps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[extensions]
DictionariesExt = "Dictionaries"
StructArraysExt = "StructArrays"

[compat]
Accessors = "0.1.20"
Dictionaries = "0.3"
InverseFunctions = "0.1.7"
julia = "1.6"

[extras]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
