name = "FlexiMaps"
uuid = "6394faf6-06db-4fa8-b750-35ccc60383f7"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.0"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"

[compat]
Accessors = "0.1.20"
julia = "1.6"
