name = "FlexiMaps"
uuid = "6394faf6-06db-4fa8-b750-35ccc60383f7"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.24"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
InverseFunctions = "3587e190-3f89-42d0-90ee-14403ec27112"

[weakdeps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"

[extensions]
DictionariesExt = "Dictionaries"
IntervalSetsExt = "IntervalSets"
StructArraysExt = "StructArrays"

[compat]
Accessors = "0.1.20"
DataPipes = "0.3.8"
Dictionaries = "0.3, 0.4"
IntervalSets = "0.7"
InverseFunctions = "0.1.7"
StructArrays = "0.6.12"
julia = "1.9"
